const description =
  "The King's Creations! An NFT Project by ALL HAIL THE KING. B2/C1 - Second Batch/First Collection.";
const baseUri = "https://straight-line.org/thekingscreations/b2/c1";

const layerConfigurations = [
  {
    // growEditionSizeTo: 1715,
    growEditionSizeTo: 5,
    layersOrder: [
      { name: "Backgrounds" },
      // { name: "Mixed Flats" },
      // { name: "Mixed Rounds" },
      // { name: "Mixed Slashes" },
      { name: "Flat Scribbles" },
      { name: "Round Scribbles" },
      { name: "Slash Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 3430,
    growEditionSizeTo: 10,
    layersOrder: [
      { name: "Backgrounds" },
      // { name: "Mixed Flats" },
      // { name: "Mixed Rounds" },
      // { name: "Mixed Slashes" },
      { name: "Flat Scribbles" },
      { name: "Slash Scribbles" },
      { name: "Round Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 5145,
    growEditionSizeTo: 15,
    layersOrder: [
      { name: "Backgrounds" },
      // { name: "Mixed Flats" },
      // { name: "Mixed Rounds" },
      // { name: "Mixed Slashes" },
      { name: "Round Scribbles" },
      { name: "Slash Scribbles" },
      { name: "Flat Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 6860,
    growEditionSizeTo: 20,
    layersOrder: [
      { name: "Backgrounds" },
      // { name: "Mixed Flats" },
      // { name: "Mixed Rounds" },
      // { name: "Mixed Slashes" },
      { name: "Round Scribbles" },
      { name: "Flat Scribbles" },
      { name: "Slash Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 8575,
    growEditionSizeTo: 25,
    layersOrder: [
      { name: "Backgrounds" },
      // { name: "Mixed Flats" },
      // { name: "Mixed Rounds" },
      // { name: "Mixed Slashes" },
      { name: "Slash Scribbles" },
      { name: "Flat Scribbles" },
      { name: "Round Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 10290,
    growEditionSizeTo: 30,
    layersOrder: [
      { name: "Backgrounds" },
      // { name: "Mixed Flats" },
      // { name: "Mixed Rounds" },
      // { name: "Mixed Slashes" },
      { name: "Slash Scribbles" },
      { name: "Round Scribbles" },
      { name: "Flat Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 10535,
    growEditionSizeTo: 35,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Flats" },
      // { name: "Mixed Rounds" },
      // { name: "Mixed Slashes" },
      // { name: "Flat Scribbles" },
      { name: "Round Scribbles" },
      { name: "Slash Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 10780,
    growEditionSizeTo: 40,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Flats" },
      // { name: "Mixed Rounds" },
      // { name: "Mixed Slashes" },
      // { name: "Flat Scribbles" },
      { name: "Slash Scribbles" },
      { name: "Round Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11025,
    growEditionSizeTo: 45,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Rounds" },
      // { name: "Mixed Flats" },
      // { name: "Mixed Slashes" },
      // { name: "Round Scribbles" },
      { name: "Slash Scribbles" },
      { name: "Flat Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11270,
    growEditionSizeTo: 50,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Rounds" },
      // { name: "Mixed Flats" },
      // { name: "Mixed Slashes" },
      // { name: "Round Scribbles" },
      { name: "Flat Scribbles" },
      { name: "Slash Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11515,
    growEditionSizeTo: 55,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Slashes" },
      // { name: "Mixed Flats" },
      // { name: "Mixed Rounds" },
      // { name: "Slash Scribbles" },
      { name: "Flat Scribbles" },
      { name: "Round Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11760,
    growEditionSizeTo: 60,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Slashes" },
      // { name: "Mixed Flats" },
      // { name: "Mixed Rounds" },
      // { name: "Slash Scribbles" },
      { name: "Round Scribbles" },
      { name: "Flat Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11795,
    growEditionSizeTo: 65,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Flats" },
      { name: "Mixed Rounds" },
      // { name: "Mixed Slashes" },
      // { name: "Flat Scribbles" },
      // { name: "Round Scribbles" },
      { name: "Slash Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11830,
    growEditionSizeTo: 70,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Flats" },
      { name: "Mixed Slashes" },
      // { name: "Mixed Rounds" },
      // { name: "Flat Scribbles" },
      // { name: "Slash Scribbles" },
      { name: "Round Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11865,
    growEditionSizeTo: 75,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Rounds" },
      { name: "Mixed Slashes" },
      // { name: "Mixed Flats" },
      // { name: "Slash Scribbles" },
      // { name: "Round Scribbles" },
      { name: "Flat Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11900,
    growEditionSizeTo: 80,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Rounds" },
      { name: "Mixed Flats" },
      // { name: "Mixed Slashes" },
      // { name: "Round Scribbles" },
      // { name: "Flat Scribbles" },
      { name: "Slash Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11935,
    growEditionSizeTo: 85,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Slashes" },
      { name: "Mixed Flats" },
      // { name: "Mixed Rounds" },
      // { name: "Flat Scribbles" },
      // { name: "Slash Scribbles" },
      { name: "Round Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11970,
    growEditionSizeTo: 90,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Slashes" },
      { name: "Mixed Rounds" },
      // { name: "Mixed Flats" },
      // { name: "Slash Scribbles" },
      // { name: "Round Scribbles" },
      { name: "Flat Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11975,
    growEditionSizeTo: 95,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Flats" },
      { name: "Mixed Rounds" },
      { name: "Mixed Slashes" },
      // { name: "Slash Scribbles" },
      // { name: "Round Scribbles" },
      // { name: "Flat Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11980,
    growEditionSizeTo: 100,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Flats" },
      { name: "Mixed Slashes" },
      { name: "Mixed Rounds" },
      // { name: "Slash Scribbles" },
      // { name: "Round Scribbles" },
      // { name: "Flat Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11985,
    growEditionSizeTo: 105,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Rounds" },
      { name: "Mixed Slashes" },
      { name: "Mixed Flats" },
      // { name: "Slash Scribbles" },
      // { name: "Round Scribbles" },
      // { name: "Flat Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11990,
    growEditionSizeTo: 110,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Rounds" },
      { name: "Mixed Flats" },
      { name: "Mixed Slashes" },
      // { name: "Slash Scribbles" },
      // { name: "Round Scribbles" },
      // { name: "Flat Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 11995,
    growEditionSizeTo: 115,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Slashes" },
      { name: "Mixed Flats" },
      { name: "Mixed Rounds" },
      // { name: "Slash Scribbles" },
      // { name: "Round Scribbles" },
      // { name: "Flat Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
  {
    // growEditionSizeTo: 12000,
    growEditionSizeTo: 120,
    layersOrder: [
      { name: "Backgrounds" },
      { name: "Mixed Slashes" },
      { name: "Mixed Rounds" },
      { name: "Mixed Flats" },
      // { name: "Slash Scribbles" },
      // { name: "Round Scribbles" },
      // { name: "Flat Scribbles" },
      { name: "Masterpiece Arts" },
    ],
  },
];

const format = {
  width: 2474,
  height: 2474,
};

const background = {
  generate: true,
  brightness: "20%",
};

const rarityDelimiter = "#";

const uniqueDnaTorrance = 12000;

module.exports = {
  format,
  baseUri,
  description,
  background,
  uniqueDnaTorrance,
  layerConfigurations,
  rarityDelimiter,
};
